--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1334.0000, height = 750.0000})

--Create bg_view
local bg_view = ccui.Layout:create()
bg_view:ignoreContentAdaptWithSize(false)
bg_view:setClippingEnabled(false)
bg_view:setBackGroundColorOpacity(127)
bg_view:setTouchEnabled(true);
bg_view:setLayoutComponentEnabled(true)
bg_view:setName("bg_view")
bg_view:setTag(21)
bg_view:setCascadeColorEnabled(true)
bg_view:setCascadeOpacityEnabled(true)
bg_view:setAnchorPoint(0.5000, 0.5000)
bg_view:setPosition(667.0000, 375.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.2369)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1650.0000, height = 750.0000})
layout:setLeftMargin(-158.0000)
layout:setRightMargin(-158.0000)
Layer:addChild(bg_view)

--Create tip_parent_view
local tip_parent_view = ccui.Layout:create()
tip_parent_view:ignoreContentAdaptWithSize(false)
tip_parent_view:setClippingEnabled(false)
tip_parent_view:setBackGroundImageCapInsets({x = -32, y = -14, width = 64, height = 28})
tip_parent_view:setBackGroundColorOpacity(102)
tip_parent_view:setBackGroundImageScale9Enabled(true)
tip_parent_view:setLayoutComponentEnabled(true)
tip_parent_view:setName("tip_parent_view")
tip_parent_view:setTag(24)
tip_parent_view:setCascadeColorEnabled(true)
tip_parent_view:setCascadeOpacityEnabled(true)
tip_parent_view:setAnchorPoint(0.5000, 0.5000)
tip_parent_view:setPosition(667.0000, 375.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_parent_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6132)
layout:setPercentHeight(0.1227)
layout:setSize({width = 818.0000, height = 92.0000})
layout:setLeftMargin(258.0000)
layout:setRightMargin(258.0000)
layout:setTopMargin(329.0000)
layout:setBottomMargin(329.0000)
Layer:addChild(tip_parent_view)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("frame_res/pictrue/hall_tips_shadow.png",0)
Image_2:setScale9Enabled(true)
Image_2:setCapInsets({x = 32, y = 19, width = 380, height = 14})
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(7)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(409.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5428)
layout:setPercentHeight(0.5652)
layout:setSize({width = 444.0000, height = 52.0000})
layout:setLeftMargin(187.0000)
layout:setRightMargin(187.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(20.0000)
tip_parent_view:addChild(Image_2)

--Create tip_panel
local tip_panel = ccui.Layout:create()
tip_panel:ignoreContentAdaptWithSize(false)
tip_panel:setClippingEnabled(false)
tip_panel:setBackGroundColorOpacity(102)
tip_panel:setTouchEnabled(true);
tip_panel:setLayoutComponentEnabled(true)
tip_panel:setName("tip_panel")
tip_panel:setTag(42)
tip_panel:setCascadeColorEnabled(true)
tip_panel:setCascadeOpacityEnabled(true)
tip_panel:setAnchorPoint(0.5000, 0.5000)
tip_panel:setPosition(409.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2445)
layout:setPercentHeight(0.5326)
layout:setSize({width = 200.0000, height = 49.0000})
layout:setLeftMargin(309.0000)
layout:setRightMargin(309.0000)
layout:setTopMargin(21.5000)
layout:setBottomMargin(21.5000)
tip_parent_view:addChild(tip_panel)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("frame_res/pictrue/currency_load.png",0)
Image_1:setFlippedX(true)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(18)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(20.0000, 24.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1800)
layout:setPercentHeight(0.7347)
layout:setSize({width = 36.0000, height = 36.0000})
layout:setLeftMargin(2.0000)
layout:setRightMargin(162.0000)
layout:setTopMargin(6.5000)
layout:setBottomMargin(6.5000)
tip_panel:addChild(Image_1)

--Create tipText
local tipText = ccui.Text:create()
tipText:ignoreContentAdaptWithSize(true)
tipText:setTextAreaSize({width = 0, height = 0})
tipText:setFontSize(27)
tipText:setString([[请稍后。。。]])
tipText:setTextHorizontalAlignment(1)
tipText:setTextVerticalAlignment(1)
tipText:setLayoutComponentEnabled(true)
tipText:setName("tipText")
tipText:setTag(25)
tipText:setCascadeColorEnabled(true)
tipText:setCascadeOpacityEnabled(true)
tipText:setAnchorPoint(0.0000, 0.5000)
tipText:setPosition(48.0000, 24.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(tipText)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2400)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8100)
layout:setPercentHeight(0.6327)
layout:setSize({width = 162.0000, height = 31.0000})
layout:setLeftMargin(48.0000)
layout:setRightMargin(-10.0000)
layout:setTopMargin(9.0000)
layout:setBottomMargin(9.0000)
tip_panel:addChild(tipText)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

