--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1334.0000, height = 750.0000})

--Create panel_noTouch
local panel_noTouch = ccui.Layout:create()
panel_noTouch:ignoreContentAdaptWithSize(false)
panel_noTouch:setClippingEnabled(false)
panel_noTouch:setBackGroundColorOpacity(102)
panel_noTouch:setTouchEnabled(true);
panel_noTouch:setLayoutComponentEnabled(true)
panel_noTouch:setName("panel_noTouch")
panel_noTouch:setTag(29)
panel_noTouch:setCascadeColorEnabled(true)
panel_noTouch:setCascadeOpacityEnabled(true)
panel_noTouch:setAnchorPoint(0.5000, 0.0000)
panel_noTouch:setPosition(667.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(panel_noTouch)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.2369)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1650.0000, height = 750.0000})
layout:setLeftMargin(-158.0000)
layout:setRightMargin(-158.0000)
Layer:addChild(panel_noTouch)

--Create tip_panel
local tip_panel = ccui.Layout:create()
tip_panel:ignoreContentAdaptWithSize(false)
tip_panel:setClippingEnabled(false)
tip_panel:setBackGroundColorOpacity(102)
tip_panel:setLayoutComponentEnabled(true)
tip_panel:setName("tip_panel")
tip_panel:setTag(113)
tip_panel:setCascadeColorEnabled(true)
tip_panel:setCascadeOpacityEnabled(true)
tip_panel:setAnchorPoint(0.5000, 0.5000)
tip_panel:setPosition(667.0000, 420.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5600)
layout:setPercentWidth(0.6132)
layout:setPercentHeight(0.1227)
layout:setSize({width = 818.0000, height = 92.0000})
layout:setLeftMargin(258.0000)
layout:setRightMargin(258.0000)
layout:setTopMargin(284.0000)
layout:setBottomMargin(374.0000)
Layer:addChild(tip_panel)

--Create Image_6
local Image_6 = ccui.ImageView:create()
Image_6:ignoreContentAdaptWithSize(false)
Image_6:loadTexture("frame_res/pictrue/hall_tips_shadow.png",0)
Image_6:setScale9Enabled(true)
Image_6:setCapInsets({x = 110, y = 16, width = 224, height = 20})
Image_6:setLayoutComponentEnabled(true)
Image_6:setName("Image_6")
Image_6:setTag(114)
Image_6:setCascadeColorEnabled(true)
Image_6:setCascadeOpacityEnabled(true)
Image_6:setPosition(409.0000, 46.0000)
Image_6:setOpacity(204)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_6)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5428)
layout:setPercentHeight(0.5652)
layout:setSize({width = 444.0000, height = 52.0000})
layout:setLeftMargin(187.0000)
layout:setRightMargin(187.0000)
layout:setTopMargin(20.0000)
layout:setBottomMargin(20.0000)
tip_panel:addChild(Image_6)

--Create tip_text
local tip_text = ccui.Text:create()
tip_text:ignoreContentAdaptWithSize(true)
tip_text:setTextAreaSize({width = 0, height = 0})
tip_text:setFontSize(27)
tip_text:setString([[这是提示文字的占位符]])
tip_text:setTextHorizontalAlignment(1)
tip_text:setTextVerticalAlignment(1)
tip_text:setLayoutComponentEnabled(true)
tip_text:setName("tip_text")
tip_text:setTag(115)
tip_text:setCascadeColorEnabled(true)
tip_text:setCascadeOpacityEnabled(true)
tip_text:setPosition(409.0000, 46.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(tip_text)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3301)
layout:setPercentHeight(0.3370)
layout:setSize({width = 270.0000, height = 31.0000})
layout:setLeftMargin(274.0000)
layout:setRightMargin(274.0000)
layout:setTopMargin(30.5000)
layout:setBottomMargin(30.5000)
tip_panel:addChild(tip_text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

