--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1334.0000, height = 750.0000})

--Create Image_6
local Image_6 = ccui.ImageView:create()
Image_6:ignoreContentAdaptWithSize(false)
Image_6:loadTexture("frame_res/pictrue/loading_background1_1.png",0)
Image_6:setLayoutComponentEnabled(true)
Image_6:setName("Image_6")
Image_6:setTag(59)
Image_6:setCascadeColorEnabled(true)
Image_6:setCascadeOpacityEnabled(true)
Image_6:setPosition(667.0000, 375.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_6)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.2181)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1625.0000, height = 750.0000})
layout:setLeftMargin(-145.5000)
layout:setRightMargin(-145.5000)
Layer:addChild(Image_6)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("frame_res/pictrue/logo.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(44)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(812.5000, 450.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6000)
layout:setPercentWidth(0.3674)
layout:setPercentHeight(0.4920)
layout:setSize({width = 597.0000, height = 369.0000})
layout:setLeftMargin(514.0000)
layout:setRightMargin(514.0000)
layout:setTopMargin(115.5000)
layout:setBottomMargin(265.5000)
Image_6:addChild(Image_2)

--Create Text_Version
local Text_Version = ccui.Text:create()
Text_Version:ignoreContentAdaptWithSize(true)
Text_Version:setTextAreaSize({width = 0, height = 0})
Text_Version:setFontSize(28)
Text_Version:setString([[1.0.0]])
Text_Version:setTextHorizontalAlignment(2)
Text_Version:setLayoutComponentEnabled(true)
Text_Version:setName("Text_Version")
Text_Version:setTag(11)
Text_Version:setCascadeColorEnabled(true)
Text_Version:setCascadeOpacityEnabled(true)
Text_Version:setVisible(false)
Text_Version:setAnchorPoint(1.0000, 0.5000)
Text_Version:setPosition(1307.3200, 21.8087)
Text_Version:setTextColor({r = 203, g = 231, b = 255})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_Version)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.9800)
layout:setPositionPercentY(0.0291)
layout:setPercentWidth(0.0472)
layout:setPercentHeight(0.0427)
layout:setSize({width = 63.0000, height = 32.0000})
layout:setLeftMargin(1244.3200)
layout:setRightMargin(26.6799)
layout:setTopMargin(712.1913)
layout:setBottomMargin(5.8087)
Layer:addChild(Text_Version)

--Create Panel_Progress
local Panel_Progress = ccui.Layout:create()
Panel_Progress:ignoreContentAdaptWithSize(false)
Panel_Progress:setClippingEnabled(false)
Panel_Progress:setBackGroundColorOpacity(102)
Panel_Progress:setTouchEnabled(true);
Panel_Progress:setLayoutComponentEnabled(true)
Panel_Progress:setName("Panel_Progress")
Panel_Progress:setTag(68)
Panel_Progress:setCascadeColorEnabled(true)
Panel_Progress:setCascadeOpacityEnabled(true)
Panel_Progress:setAnchorPoint(0.5000, 0.0000)
Panel_Progress:setPosition(667.0000, 43.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Progress)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0573)
layout:setPercentWidth(0.9095)
layout:setPercentHeight(0.2000)
layout:setSize({width = 1213.2200, height = 150.0000})
layout:setLeftMargin(60.3900)
layout:setRightMargin(60.3900)
layout:setTopMargin(557.0000)
layout:setBottomMargin(43.0000)
Layer:addChild(Panel_Progress)

--Create tip_text
local tip_text = ccui.Text:create()
tip_text:ignoreContentAdaptWithSize(true)
tip_text:setTextAreaSize({width = 0, height = 0})
tip_text:setFontSize(26)
tip_text:setString([[获取配置中，请稍后...]])
tip_text:enableShadow({r = 215, g = 246, b = 208, a = 255}, {width = 0.5, height = -0.5}, 0)
tip_text:setLayoutComponentEnabled(true)
tip_text:setName("tip_text")
tip_text:setTag(69)
tip_text:setCascadeColorEnabled(true)
tip_text:setCascadeOpacityEnabled(true)
tip_text:setPosition(620.3520, -300.9901)
tip_text:setTextColor({r = 246, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(tip_text)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5113)
layout:setPositionPercentY(-2.0066)
layout:setPercentWidth(0.2110)
layout:setPercentHeight(0.2067)
layout:setSize({width = 256.0000, height = 31.0000})
layout:setLeftMargin(492.3520)
layout:setRightMargin(464.8680)
layout:setTopMargin(435.4901)
layout:setBottomMargin(-316.4901)
Panel_Progress:addChild(tip_text)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("frame_res/pictrue/loading_background2.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(70)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(606.6100, 81.1500)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5410)
layout:setPercentWidth(0.8061)
layout:setPercentHeight(0.3467)
layout:setSize({width = 978.0000, height = 52.0000})
layout:setLeftMargin(117.6100)
layout:setRightMargin(117.6100)
layout:setTopMargin(42.8500)
layout:setBottomMargin(55.1500)
Panel_Progress:addChild(Image_1)

--Create download_progress_bar
local download_progress_bar = ccui.LoadingBar:create()
download_progress_bar:loadTexture("frame_res/pictrue/loading_background3.png",0)
download_progress_bar:ignoreContentAdaptWithSize(false)
download_progress_bar:setLayoutComponentEnabled(true)
download_progress_bar:setName("download_progress_bar")
download_progress_bar:setTag(71)
download_progress_bar:setCascadeColorEnabled(true)
download_progress_bar:setCascadeOpacityEnabled(true)
download_progress_bar:setAnchorPoint(0.0000, 0.0000)
download_progress_bar:setPosition(11.5786, 19.1549)
download_progress_bar:setOpacity(247)
layout = ccui.LayoutComponent:bindLayoutComponent(download_progress_bar)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0118)
layout:setPositionPercentY(0.3684)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(0.9755)
layout:setPercentHeight(0.5000)
layout:setSize({width = 954.0000, height = 26.0000})
layout:setLeftMargin(11.5786)
layout:setRightMargin(12.4215)
layout:setTopMargin(6.8451)
layout:setBottomMargin(19.1549)
Image_1:addChild(download_progress_bar)

--Create progress_text
local progress_text = ccui.TextAtlas:create([[0]],
													"frame_res/pictrue/login_loading_number.png",
													19,
													24,
													".")
progress_text:setLayoutComponentEnabled(true)
progress_text:setName("progress_text")
progress_text:setTag(60)
progress_text:setCascadeColorEnabled(true)
progress_text:setCascadeOpacityEnabled(true)
progress_text:setAnchorPoint(1.0000, 0.5000)
progress_text:setPosition(518.7461, -177.5017)
layout = ccui.LayoutComponent:bindLayoutComponent(progress_text)
layout:setPositionPercentX(0.4276)
layout:setPositionPercentY(-1.1833)
layout:setPercentWidth(0.0157)
layout:setPercentHeight(0.1600)
layout:setSize({width = 19.0000, height = 24.0000})
layout:setLeftMargin(499.7461)
layout:setRightMargin(694.4739)
layout:setTopMargin(315.5017)
layout:setBottomMargin(-189.5017)
Panel_Progress:addChild(progress_text)

--Create Sprite_2
local Sprite_2 = cc.Sprite:create("frame_res/pictrue/login_loading_number_unit.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setTag(62)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setPosition(531.1357, -177.5017)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentX(0.4378)
layout:setPositionPercentY(-1.1833)
layout:setPercentWidth(0.0173)
layout:setPercentHeight(0.1600)
layout:setSize({width = 21.0000, height = 24.0000})
layout:setLeftMargin(520.6357)
layout:setRightMargin(671.5842)
layout:setTopMargin(315.5017)
layout:setBottomMargin(-189.5017)
Sprite_2:setBlendFunc({src = 1, dst = 771})
Panel_Progress:addChild(Sprite_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

