--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1334.0000, height = 750.0000})

--Create bg_panel
local bg_panel = ccui.Layout:create()
bg_panel:ignoreContentAdaptWithSize(false)
bg_panel:setClippingEnabled(false)
bg_panel:setBackGroundColorType(1)
bg_panel:setBackGroundColor({r = 0, g = 0, b = 0})
bg_panel:setBackGroundColorOpacity(102)
bg_panel:setTouchEnabled(true);
bg_panel:setLayoutComponentEnabled(true)
bg_panel:setName("bg_panel")
bg_panel:setTag(16)
bg_panel:setCascadeColorEnabled(true)
bg_panel:setCascadeOpacityEnabled(true)
bg_panel:setAnchorPoint(0.5000, 0.5000)
bg_panel:setPosition(668.0672, 375.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5008)
layout:setPositionPercentY(0.5000)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.2181)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1625.0000, height = 750.0000})
layout:setLeftMargin(-144.4328)
layout:setRightMargin(-146.5671)
Layer:addChild(bg_panel)

--Create alert_view
local alert_view = ccui.Layout:create()
alert_view:ignoreContentAdaptWithSize(false)
alert_view:setBackGroundImage("frame_res/pictrue/login_small_board.png",0)
alert_view:setClippingEnabled(false)
alert_view:setBackGroundImageCapInsets({x = 183, y = 70, width = 351, height = 279})
alert_view:setBackGroundImageScale9Enabled(true)
alert_view:setTouchEnabled(true);
alert_view:setLayoutComponentEnabled(true)
alert_view:setName("alert_view")
alert_view:setTag(17)
alert_view:setCascadeColorEnabled(true)
alert_view:setCascadeOpacityEnabled(true)
alert_view:setAnchorPoint(0.5000, 0.5000)
alert_view:setPosition(667.0000, 375.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(alert_view)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5375)
layout:setPercentHeight(0.5587)
layout:setSize({width = 717.0000, height = 419.0000})
layout:setLeftMargin(308.5000)
layout:setRightMargin(308.5000)
layout:setTopMargin(165.5000)
layout:setBottomMargin(165.5000)
Layer:addChild(alert_view)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("frame_res/pictrue/zjh_room_help_table.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(37)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(358.5000, 171.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4081)
layout:setPercentWidth(0.9344)
layout:setPercentHeight(0.7494)
layout:setSize({width = 670.0000, height = 314.0000})
layout:setLeftMargin(23.5000)
layout:setRightMargin(23.5000)
layout:setTopMargin(91.0000)
layout:setBottomMargin(14.0000)
alert_view:addChild(Image_3)

--Create contentTextNode
local contentTextNode = ccui.Text:create()
contentTextNode:ignoreContentAdaptWithSize(false)
contentTextNode:setFontSize(30)
contentTextNode:setString([[提示框的文字 提示框的文字 提示框的文字 提示框的文字 提示框的文字]])
contentTextNode:setTextHorizontalAlignment(1)
contentTextNode:setTextVerticalAlignment(1)
contentTextNode:enableShadow({r = 48, g = 66, b = 116, a = 255}, {width = 0.5, height = -0.5}, 0)
contentTextNode:setLayoutComponentEnabled(true)
contentTextNode:setName("contentTextNode")
contentTextNode:setTag(18)
contentTextNode:setCascadeColorEnabled(true)
contentTextNode:setCascadeOpacityEnabled(true)
contentTextNode:setPosition(358.4283, 241.0001)
contentTextNode:setTextColor({r = 48, g = 66, b = 116})
layout = ccui.LayoutComponent:bindLayoutComponent(contentTextNode)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4999)
layout:setPositionPercentY(0.5752)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(0.8843)
layout:setPercentHeight(0.3914)
layout:setSize({width = 634.0431, height = 164.0000})
layout:setLeftMargin(41.4068)
layout:setRightMargin(41.5502)
layout:setTopMargin(95.9999)
layout:setBottomMargin(159.0001)
alert_view:addChild(contentTextNode)

--Create confirmBtn
local confirmBtn = ccui.Button:create()
confirmBtn:ignoreContentAdaptWithSize(false)
confirmBtn:loadTextureNormal("frame_res/pictrue/login_ensure_button.png",0)
confirmBtn:setTitleFontSize(30)
confirmBtn:setTitleColor({r = 65, g = 65, b = 70})
confirmBtn:setScale9Enabled(true)
confirmBtn:setCapInsets({x = 15, y = 11, width = 197, height = 75})
confirmBtn:setLayoutComponentEnabled(true)
confirmBtn:setName("confirmBtn")
confirmBtn:setTag(19)
confirmBtn:setCascadeColorEnabled(true)
confirmBtn:setCascadeOpacityEnabled(true)
confirmBtn:setPosition(501.9000, 63.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(confirmBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.7000)
layout:setPositionPercentY(0.1504)
layout:setPercentWidth(0.3166)
layout:setPercentHeight(0.2315)
layout:setSize({width = 227.0000, height = 97.0000})
layout:setLeftMargin(388.4000)
layout:setRightMargin(101.6000)
layout:setTopMargin(307.5000)
layout:setBottomMargin(14.5000)
alert_view:addChild(confirmBtn)

--Create cancelBtn
local cancelBtn = ccui.Button:create()
cancelBtn:ignoreContentAdaptWithSize(false)
cancelBtn:loadTextureNormal("frame_res/pictrue/hall_player_cancel_button.png",0)
cancelBtn:setTitleFontSize(30)
cancelBtn:setTitleColor({r = 65, g = 65, b = 70})
cancelBtn:setScale9Enabled(true)
cancelBtn:setCapInsets({x = 15, y = 11, width = 197, height = 75})
cancelBtn:setLayoutComponentEnabled(true)
cancelBtn:setName("cancelBtn")
cancelBtn:setTag(21)
cancelBtn:setCascadeColorEnabled(true)
cancelBtn:setCascadeOpacityEnabled(true)
cancelBtn:setPosition(215.1000, 64.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cancelBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.3000)
layout:setPositionPercentY(0.1527)
layout:setPercentWidth(0.3166)
layout:setPercentHeight(0.2315)
layout:setSize({width = 227.0000, height = 97.0000})
layout:setLeftMargin(101.6000)
layout:setRightMargin(388.4000)
layout:setTopMargin(306.5000)
layout:setBottomMargin(15.5000)
alert_view:addChild(cancelBtn)

--Create close_btn
local close_btn = ccui.Button:create()
close_btn:ignoreContentAdaptWithSize(false)
close_btn:loadTextureNormal("frame_res/pictrue/zjh_room_close_button.png",0)
close_btn:setTitleFontSize(14)
close_btn:setTitleColor({r = 65, g = 65, b = 70})
close_btn:setScale9Enabled(true)
close_btn:setCapInsets({x = 15, y = 11, width = 73, height = 81})
close_btn:setLayoutComponentEnabled(true)
close_btn:setName("close_btn")
close_btn:setTag(19)
close_btn:setCascadeColorEnabled(true)
close_btn:setCascadeOpacityEnabled(true)
close_btn:setAnchorPoint(0.5347, 0.5314)
close_btn:setPosition(694.7615, 392.1097)
layout = ccui.LayoutComponent:bindLayoutComponent(close_btn)
layout:setPositionPercentX(0.9690)
layout:setPositionPercentY(0.9358)
layout:setPercentWidth(0.1437)
layout:setPercentHeight(0.2458)
layout:setSize({width = 103.0000, height = 103.0000})
layout:setLeftMargin(639.6874)
layout:setRightMargin(-25.6874)
layout:setTopMargin(-21.3755)
layout:setBottomMargin(337.3755)
alert_view:addChild(close_btn)

--Create login_tips_title_1
local login_tips_title_1 = cc.Sprite:create("frame_res/pictrue/login_tips_title.png")
login_tips_title_1:setName("login_tips_title_1")
login_tips_title_1:setTag(35)
login_tips_title_1:setCascadeColorEnabled(true)
login_tips_title_1:setCascadeOpacityEnabled(true)
login_tips_title_1:setPosition(359.0019, 381.2900)
layout = ccui.LayoutComponent:bindLayoutComponent(login_tips_title_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5007)
layout:setPositionPercentY(0.9100)
layout:setPercentWidth(0.1869)
layout:setPercentHeight(0.1313)
layout:setSize({width = 134.0000, height = 55.0000})
layout:setLeftMargin(292.0019)
layout:setRightMargin(290.9981)
layout:setTopMargin(10.2100)
layout:setBottomMargin(353.7900)
login_tips_title_1:setBlendFunc({src = 1, dst = 771})
alert_view:addChild(login_tips_title_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

